### PR TITLE
Users 2.1

### PR DESCRIPTION
**Pull request by huanle25**
1. Added Subject Model to give us more control to the database. 
2. a small function to update user classroom.

### CODE REVIEW

**Review by ChanceNason — CHANGES_REQUESTED** [review]
Looks okay. Just delete course.json file (10k lines lol)

**Review by shonjs1 — CHANGES_REQUESTED** [review]
Let's remove the course_db/courses.json file. Since you ported to DB.

**Comment by huanle25** [comment]
removed course.json

**Review by shonjs1 — APPROVED** [review]
LGTM!

**Review by A-Zayed — APPROVED** [review]

**Comment by huanle25** [comment]
> Looks okay. Just delete course.json file (10k lines lol)

Approve me Chanceeeeeeeeeeeeeeee @ChanceNason

**Review by ChanceNason — APPROVED** [review]

**Pull request merged**
